server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/api/projects/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
