CREATE TABLE IF NOT EXISTS public.tt_sprint_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    change_date timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    modified_at timestamp(6) without time zone,
    new_state character varying(255) COLLATE pg_catalog."default",
    previous_state character varying(255) COLLATE pg_catalog."default",
    sprint_id bigint,
    CONSTRAINT tt_sprint_history_pkey PRIMARY KEY (id),
    CONSTRAINT fkolw9cvstm7tilxacgeieh7e2w FOREIGN KEY (sprint_id)
        REFERENCES public.tt_sprint (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.tt_task_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    change_date timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    modified_at timestamp(6) without time zone,
    new_state character varying(255) COLLATE pg_catalog."default",
    previous_state character varying(255) COLLATE pg_catalog."default",
    task_id bigint,
    CONSTRAINT tt_task_history_pkey PRIMARY KEY (id),
    CONSTRAINT fkbtsdmh2de7nrmip3rrgo61idq FOREIGN KEY (task_id)
        REFERENCES public.tt_task (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.tt_project_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    change_date timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    modified_at timestamp(6) without time zone,
    new_state character varying(255) COLLATE pg_catalog."default",
    previous_state character varying(255) COLLATE pg_catalog."default",
    project_id bigint,
    CONSTRAINT tt_project_history_pkey PRIMARY KEY (id),
    CONSTRAINT fkbeddblxhr2cnsshojfkj9070b FOREIGN KEY (project_id)
        REFERENCES public.tt_projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);


