CREATE TABLE IF NOT EXISTS public.tt_role
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tt_role_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tt_permission
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    etat character varying(255) COLLATE pg_catalog."default",
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tt_permission_pkey PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.tt_role_permission
(
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL,
    CONSTRAINT fkh7928mhcuj4ljxg6win1rj3ni FOREIGN KEY (permission_id)
        REFERENCES public.tt_permission (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkm486jcme0m1pvhy6h56goqu57 FOREIGN KEY (role_id)
        REFERENCES public.tt_role (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.tt_speciality
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tt_speciality_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tt_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default",
    pre_name character varying(255) COLLATE pg_catalog."default",
    role_id bigint,
    CONSTRAINT tt_user_pkey PRIMARY KEY (id),
    CONSTRAINT uk63jw6ht8ei8ml4asyf0rishdb UNIQUE (email),
    CONSTRAINT fkryh2h51hti2m0srer5b7ivbu FOREIGN KEY (role_id)
        REFERENCES public.tt_role (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.tt_user_speciality
(
    speciality_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT fk4auglvxc1b671iu3x5t19i82u FOREIGN KEY (user_id)
        REFERENCES public.tt_speciality (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fksv953wcds9vwuxwm1crq0hnai FOREIGN KEY (speciality_id)
        REFERENCES public.tt_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS public.tt_team
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    speciality_id bigint,
    CONSTRAINT tt_team_pkey PRIMARY KEY (id),
    CONSTRAINT fkjih6lghskr0fp2i08ed1x8rb FOREIGN KEY (speciality_id)
        REFERENCES public.tt_speciality (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.tt_team_user
(
    team_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT fk7bxig6m4o7e4ywlbt7dg7lo68 FOREIGN KEY (user_id)
        REFERENCES public.tt_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fkc18ket9hxww8pb3nl0in3ttnf FOREIGN KEY (team_id)
        REFERENCES public.tt_team (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.tt_projects
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    end_date timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    start_date timestamp(6) without time zone,
    team_id bigint,
    CONSTRAINT tt_projects_pkey PRIMARY KEY (id),
    CONSTRAINT fk41xrm3hjvah5do84jr68i9wnx FOREIGN KEY (team_id)
        REFERENCES public.tt_team (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.tt_sprint
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    end_date timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    start_date timestamp(6) without time zone,
    project_id bigint,
    CONSTRAINT tt_sprint_pkey PRIMARY KEY (id),
    CONSTRAINT fksf6o779mhqx96mog47l3amemf FOREIGN KEY (project_id)
        REFERENCES public.tt_projects (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.tt_task
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    end_date timestamp(6) without time zone,
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    start_date timestamp(6) without time zone,
    sprint_id bigint,
    user_id bigint,
    CONSTRAINT tt_task_pkey PRIMARY KEY (id),
    CONSTRAINT fk1fqs7uo74v61n3mt1hcxatnbg FOREIGN KEY (user_id)
        REFERENCES public.tt_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fke7n0ouy4h4pelvy93tkcj76vk FOREIGN KEY (sprint_id)
        REFERENCES public.tt_sprint (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.tt_comment
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    created_by character varying(255) COLLATE pg_catalog."default",
    deleted boolean NOT NULL,
    message character varying(255) COLLATE pg_catalog."default",
    modified_at timestamp(6) without time zone,
    modified_by character varying(255) COLLATE pg_catalog."default",
    task_id bigint,
    user_id bigint,
    CONSTRAINT tt_comment_pkey PRIMARY KEY (id),
    CONSTRAINT fk4h08idkeyg072ojij57r9x54r FOREIGN KEY (task_id)
        REFERENCES public.tt_task (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk7x03spxk5rh2nueyl8auiixkc FOREIGN KEY (user_id)
        REFERENCES public.tt_user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);
