# Application Name
spring.application.name=tasks-service
spring.cloud.config.enabled=true
spring.cloud.config.uri=http://localhost:8888
spring.config.import=optional:configserver:
#spring.profiles.active=dev
spring.profiles.active=dev